# Titanic challenge from Kaggle

## This is the dataset from [Titanic](https://www.kaggle.com/c/titanic) Kaggle competition

### Let's import some libs

In [1]:
library(rpart)
library(zoo)
library(randomForest)

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

randomForest 4.6-14
Type rfNews() to see new features/changes/bug fixes.

In [2]:
## Now, we'll load the datasets

In [2]:
train <- read.csv("data/train.csv")
test <- read.csv("data/test.csv")

We don't have the `Survived` feature in the `test` dataset, so, we'll create it

In [3]:
test$Survived <- NA

Now, we will create a simple function that splits the data. Ok, `R` have this function, but, see, we'll to this, below, in a few lines of code.

In [4]:
splitData <- function(dataframe, seed=NULL) {
  if (!is.null(seed)) set.seed(seed)
  index <- 1:nrow(dataframe)
  
  trainindex <- sample(index, trunc(length(index)*.8))
  
  trainset <- dataframe[trainindex, ]
  
  subindex <- 1:nrow(trainset)
  validationindex <- sample(subindex, trunc(length(subindex)*.8))
  
  validationset <- dataframe[-validationindex, ]
  trainset <- trainset[validationindex, ]
  
  
  testset <- dataframe[-trainindex, ]
  list(train=trainset, test=testset, validation=validationset)
}

It's important to notice that all transformations that we'll do in `train` dataset, we need to replicate in the `test` dataset. In our case, we merged both for this reason, but, don't worry, we'll split it a few later!

In [5]:
combined <- rbind(train, test)

combined$Name <- as.character(combined$Name)
combined$Title <- sapply(combined$Name, FUN=function(x) {strsplit(x, split='[,.]')[[1]][2]})
combined$Title <- sub(' ', '', combined$Title)
combined$Title[combined$Title %in% c('Mme', 'Mlle')] <- 'Mlle'
combined$Title[combined$Title %in% c('Capt', 'Don', 'Major', 'Sir')] <- 'Sir'
combined$Title[combined$Title %in% c('Dona', 'Lady', 'the Countess', 'Jonkheer')] <- 'Lady'
combined$Title <- factor(combined$Title)
combined$FamilySize <- combined$SibSp + combined$Parch + 1
combined$Surname <- sapply(combined$Name, FUN=function(x) {strsplit(x, split='[,.]')[[1]][1]})
combined$FamilyID <- factor(paste(as.character(combined$FamilySize), combined$Surname, sep=""))

In [6]:
combined <- combined[order(combined$Surname, na.last=FALSE) , ]

combined$Age <- na.spline(combined$Age)
combined$Fare <- na.spline(combined$Fare)

Now, we will undo the train/test merge:

In [7]:
combined <- combined[order(combined$Survived, na.last=TRUE) , ]

In [8]:
full_data_combined = combined[1:891,]
split_data <- splitData(full_data_combined)
split_data$train

fit <- randomForest(as.factor(Survived) ~ Pclass + Sex + Age + Fare + Title + FamilySize + Embarked, data=full_data_combined, importance=TRUE, ntree = 2500)

prediction_test <- predict(fit, split_data$test, type = "class")
dt_test = data.frame(PassengerId = split_data$test$PassengerId, 
                     Survived_P = prediction_test, 
                     Survived = split_data$test$Survived, 
                     Correct = (split_data$test$Survived == prediction_test))


clean_test <- combined[892:1309,]
prediction <- predict(fit, clean_test, type = "class")
length(prediction)

result <- data.frame(PassengerId = clean_test$PassengerId, Survived = prediction)

    PassengerId Survived Pclass
49   49         0        3
622 622         1        1
769 769         0        3
775 775         1        2
354 354         0        3
727 727         1        2
464 464         0        2
873 873         0        1
488 488         0        1
428 428         1        2
648 648         1        1
420 420         0        3
301 301         1        3
667 667         0        2
84   84         0        1
32   32         1        1
393 393         0        3
628 628         1        1
515 515         0        3
576 576         0        3
38   38         0        3
205 205         1        3
568 568         0        3
679 679         0        3
85   85         1        2
134 134         1        2
607 607         0        3
478 478         0        3
411 411         0        3
11   11         1        3
⋮   ⋮           ⋮        ⋮
258 258         1        1
707 707         1        2
10   10         1        2
81   81         0        3
109 109         0        3
357 357         1        1
331 331         1        3
623 623         1        3
503 503         0        3
585 585         0        3
93   93         0        1
730 730         0        3
328 328         1        2
110 110         1        3
874 874         0        3
396 396         0        3
626 626         0        1
663 663         0        1
846 846         0        3
553 553         0        3
832 832         1        2
671 671         1        2
725 725         1        1
492 492         0        3
278 278         0        2
703 703         0        3
212 212         1        2
618 618         0        3
199 199         1        3
7     7         0        1
    Name                                                                Sex
49  Samaan, Mr. Youssef                                                 male
622 Kimball, Mr. Edwin Nelson Jr                                        male
769 Moran, Mr. Daniel J                                                 male
775 Hocking, Mrs. Elizabeth (Eliza Needs)                               female
354 Arnold-Franchi, Mr. Josef                                           male
727 Renouf, Mrs. Peter Henry (Lillian Jefferys)                         female
464 Milling, Mr. Jacob Christian                                        male
873 Carlsson, Mr. Frans Olof                                            male
488 Kent, Mr. Edward Austin                                             male
428 Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall") female
648 Simonius-Blumer, Col. Oberst Alfons                                 male
420 Van Impe, Miss. Catharina                                           female
301 Kelly, Miss. Anna Katherine "Annie Kate"                            female
667 Butler, Mr. Reginald Fenton                                         male
84  Carrau, Mr. Francisco M                                             male
32  Spencer, Mrs. William Augustus (Marie Eugenie)                      female
393 Gustafsson, Mr. Johan Birger                                        male
628 Longley, Miss. Gretchen Fiske                                       female
515 Coleff, Mr. Satio                                                   male
576 Patchett, Mr. George                                                male
38  Cann, Mr. Ernest Charles                                            male
205 Cohen, Mr. Gurshon "Gus"                                            male
568 Palsson, Mrs. Nils (Alma Cornelia Berglund)                         female
679 Goodwin, Mrs. Frederick (Augusta Tyler)                             female
85  Ilett, Miss. Bertha                                                 female
134 Weisz, Mrs. Leopold (Mathilde Francoise Pede)                       female
607 Karaic, Mr. Milan                                                   male
478 Braund, Mr. Lewis Richard                                           male
411 Sdycoff, Mr. Todor                                                  male
11  Sandstrom, Miss. Marguerite Rut                                     female
⋮   ⋮                                                                   ⋮
258 Cherry, Miss. Gladys                                                female
707 Kelly, Mrs. Florence "Fannie"                                       female
10  Nasser, Mrs. Nicholas (Adele Achem)                                 female
81  Waelens, Mr. Achille                                                male
109 Rekic, Mr. Tido                                                     male
357 Bowerman, Miss. Elsie Edith                                         female
331 McCoy, Miss. Agnes                                                  female
623 Nakid, Mr. Sahid                                                    male
503 O'Sullivan, Miss. Bridget Mary                                      female
585 Paulner, Mr. Uscher                                                 male
93  Chaffee, Mr. Herbert Fuller                                         male
730 Ilmakangas, Miss. Pieta Sofia                                       female
328 Ball, Mrs. (Ada E Hall)                                             female
110 Moran, Miss. Bertha                                                 female
874 Vander Cruyssen, Mr. Victor                                         male
396 Johansson, Mr. Erik                                                 male
626 Sutton, Mr. Frederick                                               male
663 Colley, Mr. Edward Pomeroy                                          male
846 Abbing, Mr. Anthony                                                 male
553 O'Brien, Mr. Timothy                                                male
832 Richards, Master. George Sibley                                     male
671 Brown, Mrs. Thomas William Solomon (Elizabeth Catherine Ford)       female
725 Chambers, Mr. Norman Campbell                                       male
492 Windelov, Mr. Einar                                                 male
278 Parkes, Mr. Francis "Frank"                                         male
703 Barbara, Miss. Saiide                                               female
212 Cameron, Miss. Clear Annie                                          female
618 Lobb, Mrs. William Arthur (Cordelia K Stanlick)                     female
199 Madigan, Miss. Margaret "Maggie"                                    female
7   McCarthy, Mr. Timothy J                                             male
    Age       SibSp Parch Ticket           Fare         Cabin       Embarked
49  28.67030  2     0     2662              21.6792                 C
622 42.00000  1     0     11753             52.5542     D19         S
769 65.76899  1     0     371110            24.1500                 Q
775 54.00000  1     3     29105             23.0000                 S
354 25.00000  1     0     349237            17.8000                 S
727 30.00000  3     0     31027             21.0000                 S
464 48.00000  0     0     234360            13.0000                 S
873 33.00000  0     0     695                5.0000     B51 B53 B55 S
488 58.00000  0     0     11771             29.7000     B37         C
428 19.00000  0     0     250655            26.0000                 S
648 56.00000  0     0     13213             35.5000     A26         C
420 10.00000  0     2     345773            24.1500                 S
301 33.44742  0     0     9234               7.7500                 Q
667 25.00000  0     0     234686            13.0000                 S
84  28.00000  0     0     113059            47.1000                 S
32  68.67214  1     0     PC 17569         146.5208     B78         C
393 28.00000  2     0     3101277            7.9250                 S
628 21.00000  0     0     13502             77.9583     D9          S
515 24.00000  0     0     349209             7.4958                 S
576 19.00000  0     0     358585            14.5000                 S
38  21.00000  0     0     A./5. 2152         8.0500                 S
205 18.00000  0     0     A/5 3540           8.0500                 S
568 29.00000  0     4     349909            21.0750                 S
679 43.00000  1     6     CA 2144           46.9000                 S
85  17.00000  0     0     SO/C 14885        10.5000                 S
134 29.00000  1     0     228414            26.0000                 S
607 30.00000  0     0     349246             7.8958                 S
478 29.00000  1     0     3460               7.0458                 S
411 22.47692  0     0     349222             7.8958                 S
11   4.00000  1     1     PP 9549           16.7000     G6          S
⋮   ⋮         ⋮     ⋮     ⋮                ⋮            ⋮           ⋮
258  30.00000 0     0     110152           8.650000e+01 B77         S
707  45.00000 0     0     223596           1.350000e+01             S
10   14.00000 1     0     237736           3.007080e+01             C
81   22.00000 0     0     345767           9.000000e+00             S
109  38.00000 0     0     349249           7.895800e+00             S
357  22.00000 0     1     113505           5.500000e+01 E33         S
331  41.38361 2     0     367226           2.325000e+01             Q
623  20.00000 1     1     2653             1.574170e+01             C
503  33.89331 0     0     330909           7.629200e+00             Q
585  29.40319 0     0     3411             8.712500e+00             C
93   46.00000 1     0     W.E.P. 5734      6.117500e+01 E31         S
730  25.00000 1     0     STON/O2. 3101271 7.925000e+00             S
328  36.00000 0     0     28551            1.300000e+01 D           S
110  64.07580 1     0     371110           2.415000e+01             Q
874  47.00000 0     0     345765           9.000000e+00             S
396  22.00000 0     0     350052           7.795800e+00             S
626  61.00000 0     0     36963            3.232080e+01 D50         S
663  47.00000 0     0     5727             2.558750e+01 E58         S
846  42.00000 0     0     C.A. 5547        7.550000e+00             S
553 144.35287 0     0     330979           7.829200e+00             Q
832   0.83000 1     1     29106            1.875000e+01             S
671  40.00000 1     1     29750            3.900000e+01             S
725  27.00000 1     0     113806           5.310000e+01 E8          S
492  21.00000 0     0     SOTON/OQ 3101317 7.250000e+00             S
278  45.76642 0     0     239853           1.776357e-15             S
703  18.00000 0     1     2691             1.445420e+01             C
212  35.00000 0     0     F.C.C. 13528     2.100000e+01             S
618  26.00000 1     0     A/5. 3336        1.610000e+01             S
199  19.87449 0     0     370370           7.750000e+00             Q
7    54.00000 0     0     17463            5.186250e+01 E46         S
    Title  FamilySize Surname         FamilyID
49  Mr     3          Samaan          3Samaan
622 Mr     2          Kimball         2Kimball
769 Mr     2          Moran           2Moran
775 Mrs    5          Hocking         5Hocking
354 Mr     2          Arnold-Franchi  2Arnold-Franchi
727 Mrs    4          Renouf          4Renouf
464 Mr     1          Milling         1Milling
873 Mr     1          Carlsson        1Carlsson
488 Mr     1          Kent            1Kent
428 Miss   1          Phillips        1Phillips
648 Col    1          Simonius-Blumer 1Simonius-Blumer
420 Miss   3          Van Impe        3Van Impe
301 Miss   1          Kelly           1Kelly
667 Mr     1          Butler          1Butler
84  Mr     1          Carrau          1Carrau
32  Mrs    2          Spencer         2Spencer
393 Mr     3          Gustafsson      3Gustafsson
628 Miss   1          Longley         1Longley
515 Mr     1          Coleff          1Coleff
576 Mr     1          Patchett        1Patchett
38  Mr     1          Cann            1Cann
205 Mr     1          Cohen           1Cohen
568 Mrs    5          Palsson         5Palsson
679 Mrs    8          Goodwin         8Goodwin
85  Miss   1          Ilett           1Ilett
134 Mrs    2          Weisz           2Weisz
607 Mr     1          Karaic          1Karaic
478 Mr     2          Braund          2Braund
411 Mr     1          Sdycoff         1Sdycoff
11  Miss   3          Sandstrom       3Sandstrom
⋮   ⋮      ⋮          ⋮               ⋮
258 Miss   1          Cherry          1Cherry
707 Mrs    1          Kelly           1Kelly
10  Mrs    2          Nasser          2Nasser
81  Mr     1          Waelens         1Waelens
109 Mr     1          Rekic           1Rekic
357 Miss   2          Bowerman        2Bowerman
331 Miss   3          McCoy           3McCoy
623 Mr     3          Nakid           3Nakid
503 Miss   1          O'Sullivan      1O'Sullivan
585 Mr     1          Paulner         1Paulner
93  Mr     2          Chaffee         2Chaffee
730 Miss   2          Ilmakangas      2Ilmakangas
328 Mrs    1          Ball            1Ball
110 Miss   2          Moran           2Moran
874 Mr     1          Vander Cruyssen 1Vander Cruyssen
396 Mr     1          Johansson       1Johansson
626 Mr     1          Sutton          1Sutton
663 Mr     1          Colley          1Colley
846 Mr     1          Abbing          1Abbing
553 Mr     1          O'Brien         1O'Brien
832 Master 3          Richards        3Richards
671 Mrs    3          Brown           3Brown
725 Mr     2          Chambers        2Chambers
492 Mr     1          Windelov        1Windelov
278 Mr     1          Parkes          1Parkes
703 Miss   2          Barbara         2Barbara
212 Miss   1          Cameron         1Cameron
618 Mrs    2          Lobb            2Lobb
199 Miss   1          Madigan         1Madigan
7   Mr     1          McCarthy        1McCarthy

[1] 418

In [9]:
write.csv(result, file = "result.csv", row.names = FALSE)